server:
  port: 8080
  
  #nohup java -jar -Dspring.profiles.active=prod animal-0.0.1-SNAPSHOT.jar > animal.log &
  
spring:
  application:
    name: animals
  profiles:
    active: default 
  rabbitmq:
    host: ec2-13-124-221-31.ap-northeast-2.compute.amazonaws.com
    username: rabbitmq
    password: password123
      
  datasource:
    url: jdbc:mysql://mysql-1.co2rhj8bx4dt.ap-northeast-2.rds.amazonaws.com/animal?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: admin
    password: password123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    show-sql: true 
    generate-ddl: true  
    properties:      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 5
        order_inserts: true
        order_updates: true
        
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.28:8761/eureka/
  instance:
    hostname: 192.168.0.28


--- 
spring:
  profiles: prod
  redis:
    host: 13.124.190.225
    port: 6379
    password: foobared
    
eureka:
  client:
    service-url:
      default-zone: http://13.124.190.225:8761/eureka/
  instance:
    hostname: ec2-13-124-190-225.ap-northeast-2.compute.amazonaws.com    

